# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Casio/Casio.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio || ORIG_REF_NAME==Casio}]

# IP: bd/Casio/ip/Casio_processing_system7_0_0/Casio_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_processing_system7_0_0 || ORIG_REF_NAME==Casio_processing_system7_0_0}]

# IP: bd/Casio/ip/Casio_axi_gpio_0_0/Casio_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_axi_gpio_0_0 || ORIG_REF_NAME==Casio_axi_gpio_0_0}]

# IP: bd/Casio/ip/Casio_axi_gpio_0_1/Casio_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_axi_gpio_0_1 || ORIG_REF_NAME==Casio_axi_gpio_0_1}]

# IP: bd/Casio/ip/Casio_ps7_0_axi_periph_0/Casio_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_ps7_0_axi_periph_0 || ORIG_REF_NAME==Casio_ps7_0_axi_periph_0}]

# IP: bd/Casio/ip/Casio_rst_ps7_0_100M_0/Casio_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_rst_ps7_0_100M_0 || ORIG_REF_NAME==Casio_rst_ps7_0_100M_0}]

# IP: bd/Casio/ip/Casio_xbar_0/Casio_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_xbar_0 || ORIG_REF_NAME==Casio_xbar_0}]

# IP: bd/Casio/ip/Casio_auto_pc_0/Casio_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Casio_auto_pc_0 || ORIG_REF_NAME==Casio_auto_pc_0}]

# XDC: bd/Casio/Casio_ooc.xdc
