# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_0_0/Casio_Design_axi_gpio_0_0.xci
# IP: The module: 'Casio_Design_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_0_0/Casio_Design_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_Design_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_0_0/Casio_Design_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_Design_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_0_0/Casio_Design_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_Design_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_0_0/Casio_Design_axi_gpio_0_0.xci
# IP: The module: 'Casio_Design_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_0_0/Casio_Design_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_Design_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_0_0/Casio_Design_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_Design_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Projects/Casioproject/Casio/Casio/Casio.srcs/sources_1/bd/Casio_Design/ip/Casio_Design_axi_gpio_0_0/Casio_Design_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_Design_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
