# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jesper Kirial/project_5/project_5.srcs/sources_1/bd/Casio/ip/Casio_xbar_0/Casio_xbar_0.xci
# IP: The module: 'Casio_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jesper Kirial/project_5/project_5.srcs/sources_1/bd/Casio/ip/Casio_xbar_0/Casio_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/Jesper Kirial/project_5/project_5.srcs/sources_1/bd/Casio/ip/Casio_xbar_0/Casio_xbar_0.xci
# IP: The module: 'Casio_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jesper Kirial/project_5/project_5.srcs/sources_1/bd/Casio/ip/Casio_xbar_0/Casio_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
