# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jesper Kirial/project_5/project_5.srcs/sources_1/bd/Casio/ip/Casio_axi_gpio_0_1/Casio_axi_gpio_0_1.xci
# IP: The module: 'Casio_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jesper Kirial/project_5/project_5.srcs/sources_1/bd/Casio/ip/Casio_axi_gpio_0_1/Casio_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Jesper Kirial/project_5/project_5.srcs/sources_1/bd/Casio/ip/Casio_axi_gpio_0_1/Casio_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Jesper Kirial/project_5/project_5.srcs/sources_1/bd/Casio/ip/Casio_axi_gpio_0_1/Casio_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Jesper Kirial/project_5/project_5.srcs/sources_1/bd/Casio/ip/Casio_axi_gpio_0_1/Casio_axi_gpio_0_1.xci
# IP: The module: 'Casio_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jesper Kirial/project_5/project_5.srcs/sources_1/bd/Casio/ip/Casio_axi_gpio_0_1/Casio_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Jesper Kirial/project_5/project_5.srcs/sources_1/bd/Casio/ip/Casio_axi_gpio_0_1/Casio_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Jesper Kirial/project_5/project_5.srcs/sources_1/bd/Casio/ip/Casio_axi_gpio_0_1/Casio_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Casio_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
